name: flutter_blue_plus_example
description: Demonstrates how to use the flutter_blue_plus plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0
  json_annotation: any
  go_router: ^6.0.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  url_launcher: ^6.0.9
  flutter_blue_plus: ^1.4.0
  flutter_colorpicker: 1.0.3
  cupertino_icons: ^1.0.2
  photo_view: 0.14.0
  image: 4.0.6
  google_sign_in: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
